language: ruby
bundler_args: --without development
before_install:
  - gem update --system
  - gem --version
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ruby-head
